### ISSUE TITLE
where academy/academy.csv

### ISSUE THREAD

**Issue by xiaokuili** [onlyphantom/llm-python#13]

**Comment by onlyphantom** [comment]
hey @xiaokuili  i didn't upload a copy of `academy.csv` as that's actually real operational data from my company Algoritma Data Science Academy (https://algorit.ma). 

I thought it's good to show how I build my LLM workflow and processes using actual data, from my actual work, rather than some dummy data. Unfortunately I can't share academy.csv --- the lessons should still apply to pretty much any csv files though!
